version: 0.2

phases:
  install:
    commands:
        - echo Setting Janapanses...
        - yum install -y glibc-langpack-ja
        - export LANG=ja_JP.UTF-8
        - export LC_ALL=${LANG}
  build:
    commands:
        - echo Executing Unit Test and Build an Artifact...
        - vendor/bin/phpunit --log-junit junit_report.xml

reports:
  junit:
    files:
      - '**/junit_report.xml'

