version: 0.2

phases:
  install:
    commands:
        - echo Setting Janapanses and PHP...
        - yum install -y glibc-langpack-ja php-devel
        - export LANG=ja_JP.UTF-8
        - export LC_ALL=${LANG}
  pre_build:
    commands:
        - echo Installing Composer...
        - composer install
        - echo Setting Xdebug...
        - export PHPINI_PATH=$(php -i | grep 'Loaded Configuration File' | awk '{print $5}')
        - echo 'xdebug.mode=coverage' >> $PHPINI_PATH
  build:
    commands:
        - echo Executing Unit Test and Build an Artifact...
        - vendor/bin/phpunit --log-junit junit_report.xml --coverage-cobertura coverage-report.xml
  post_build:
    commands:
        - echo Checking SAST...
        - vendor/bin/phpstan analyze src tests

reports:
  junit:
    files:
      - '**/junit_report.xml'
  coverage-report:
    files:
      - coverage-report.xml
    file-format: CoberturaXml

